name: 'main build status'

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: 'Build'

    runs-on: windows-latest

    steps:
    - name: Checkout files
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'
    - name: Setup NBGV
      uses: dotnet/nbgv@v0.4
      with:
        toolVersion: 3.5.119
    - name: Restore dependencies
      run: dotnet restore "${{ github.workspace }}/src/SDK.sln"
    - name: Build solution
      run: dotnet build "${{ github.workspace }}/src/SDK.sln" --no-restore -c Release