name: 'main build status'

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: 'Build'

    runs-on: windows-latest

    steps:
    - name: Checkout files
      uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@871f041373faaad213a635d9afb62905ec029bbb # v1.10.1
      with:
        dotnet-version: '10.x'
    - name: Setup NBGV
      uses: dotnet/nbgv@3cf2d96c2aa00675081b59f401356ac1fb81092f # v0.5.1
      with:
        toolVersion: 3.9.50
    - name: Restore dependencies
      run: dotnet restore "${{ github.workspace }}/src/SDK.sln"
    - name: Build solution
      run: dotnet build "${{ github.workspace }}/src/SDK.sln" --no-restore -c Release